# Generated by Django 4.2.13 on 2025-08-07 10:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0014_alter_customstatusdesc_status_alter_order_status_and_more'),
        ('user', '0007_alter_user_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, choices=[('1', 'Asosiy ombor(haydovchiga chiqim qilad oladigan)'), ('2', 'Oddiy fileal')], default='1', max_length=2, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.districts')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.regions')),
            ],
        ),
        migrations.CreateModel(
            name='Postage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(blank=True, choices=[('1', 'Seller omborga pochta topshirdi'), ('2', 'Seller ombordan pochtani qaytarib olish'), ('3', 'Haydovchi ombordan pochta oldi'), ('4', 'Haydovchi omborga pochtani qaytarib berdi'), ('5', "Filealdan filealga o'tkazma")], default=1, max_length=50, null=True)),
                ('from_user_status', models.CharField(blank=True, choices=[('1', 'Tasdiqlanmagan'), ('2', 'Tasdiqlandi'), ('3', 'Bekor qilindi')], default=1, max_length=50, null=True)),
                ('from_user_status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('to_user_status', models.CharField(blank=True, choices=[('1', 'Tasdiqlanmagan'), ('2', 'Tasdiqlandi'), ('3', 'Bekor qilindi')], default=1, max_length=50, null=True)),
                ('to_user_status_changed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_logistic_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postage_from_logistic_branch', to='postage.logisticbranch')),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postage_from_user', to=settings.AUTH_USER_MODEL)),
                ('to_logistic_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postage_to_logistic_branch', to='postage.logisticbranch')),
                ('to_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postage_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostageDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_from_user', models.BooleanField(default=False)),
                ('scan_to_user', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
                ('postage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postage.postage')),
            ],
        ),
    ]
