# Generated by Django 4.2.13 on 2025-08-07 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('postage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticBranchPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_view', models.BooleanField(default=True, verbose_name='has_view')),
                ('seller_in', models.BooleanField(default=False, verbose_name='seller_in')),
                ('seller_return', models.BooleanField(default=False, verbose_name='seller_return')),
                ('driver_out', models.BooleanField(default=False, verbose_name='driver_out')),
                ('driver_return', models.BooleanField(default=False, verbose_name='driver_return')),
                ('transfer', models.BooleanField(default=False, verbose_name='transfer')),
                ('history', models.BooleanField(default=False, verbose_name='history')),
                ('residue', models.BooleanField(default=False, verbose_name='residue')),
                ('logistic_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postage.logisticbranch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
