# Generated by Django 4.2.13 on 2025-08-07 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postage', '0002_logisticbranchpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logisticbranchpermission',
            name='seller_in',
        ),
        migrations.AddField(
            model_name='logisticbranchpermission',
            name='seller_input',
            field=models.BooleanField(default=False, verbose_name='seller_input'),
        ),
    ]
