# Generated by Django 4.2.13 on 2025-08-13 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postage', '0003_remove_logisticbranchpermission_seller_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='logisticbranchpermission',
            name='seller_history',
            field=models.BooleanField(default=True, verbose_name='seller_input'),
        ),
    ]
