# Generated by Django 4.2.13 on 2025-09-05 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postage', '0004_logisticbranchpermission_seller_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='postagedetails',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='postage',
            name='action',
            field=models.CharField(blank=True, choices=[('1', 'Seller omborga pochta topshirdi'), ('2', 'Seller ombordan pochtani qaytarib olish'), ('3', 'Haydovchi filealdan pochta oldi'), ('4', 'Haydovchi filealga pochtani qaytarib berdi'), ('5', "Filealdan filealga o'tkazma")], default=1, max_length=50, null=True),
        ),
    ]
