# Generated by Django 4.2.13 on 2025-09-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postage', '0005_postagedetails_updated_at_alter_postage_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postagedetails',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='postage',
            name='action',
            field=models.CharField(blank=True, choices=[('1', 'Seller omborga pochta topshirdi'), ('2', 'Seller ombordan pochtani qaytarib oldi'), ('3', 'Haydovchi filealdan pochta oldi'), ('4', 'Haydovchi filealga pochtani qaytarib berdi'), ('5', "Filealdan filealga o'tkazma")], default=1, max_length=50, null=True),
        ),
    ]
